import { Contact, UserPlus, ClipboardList, Ticket, Briefcase, MessageSquare } from "lucide-react"
const FORM_TEMPLATES = [
    {
      id: "contactForm",
      label: "Contact Form",
      icon: Contact,
      components: [
        {
          id: "heading_contact",
          type: "heading",
          label: "Contact Us",
          gridColumns: "full",
        },
        {
          id: "text_name",
          type: "text",
          label: "Your Name",
          required: true,
          gridColumns: "full",
        },
        {
          id: "email_contact",
          type: "email",
          label: "Email Address",
          required: true,
          gridColumns: "full",
        },
        {
          id: "tel_contact",
          type: "tel",
          label: "Phone Number",
          gridColumns: "full",
        },
        {
          id: "select_subject",
          type: "select",
          label: "Subject",
          options: ["General Inquiry", "Support", "Feedback", "Other"],
          gridColumns: "full",
        },
        {
          id: "textarea_message",
          type: "textarea",
          label: "Your Message",
          required: true,
          rows: 5,
          gridColumns: "full",
        },
        {
          id: "submit_contact",
          type: "submit",
          label: "Send Message",
          gridColumns: "full",
        },
      ],
    },
    {
      id: "registrationForm",
      label: "Registration Form",
      icon: UserPlus,
      components: [
        {
          id: "heading_registration",
          type: "heading",
          label: "Create an Account",
          gridColumns: "full",
        },
        {
          id: "fullName_registration",
          type: "fullName",
          label: "Full Name",
          required: true,
          gridColumns: "full",
        },
        {
          id: "email_registration",
          type: "email",
          label: "Email Address",
          required: true,
          gridColumns: "2",
        },
        {
          id: "tel_registration",
          type: "tel",
          label: "Phone Number",
          gridColumns: "2",
        },
        {
          id: "password_registration",
          type: "password",
          label: "Password",
          required: true,
          gridColumns: "2",
        },
        {
          id: "password_confirm",
          type: "password",
          label: "Confirm Password",
          required: true,
          gridColumns: "2",
        },
        {
          id: "checkbox_terms",
          type: "checkbox",
          label: "Terms",
          checkboxLabel: "I agree to the Terms and Conditions",
          required: true,
          gridColumns: "full",
        },
        {
          id: "submit_registration",
          type: "submit",
          label: "Create Account",
          gridColumns: "full",
        },
      ],
    },
    {
      id: "surveyForm",
      label: "Survey Form",
      icon: ClipboardList,
      components: [
        {
          id: "heading_survey",
          type: "heading",
          label: "Customer Satisfaction Survey",
          gridColumns: "full",
        },
        {
          id: "text_survey_name",
          type: "text",
          label: "Your Name (Optional)",
          gridColumns: "full",
        },
        {
          id: "email_survey",
          type: "email",
          label: "Email Address (Optional)",
          gridColumns: "full",
        },
        {
          id: "radio_satisfaction",
          type: "radio",
          label: "How satisfied are you with our service?",
          options: ["Very Satisfied", "Satisfied", "Neutral", "Dissatisfied", "Very Dissatisfied"],
          required: true,
          gridColumns: "full",
        },
        {
          id: "starRating_survey",
          type: "starRating",
          label: "Rate your overall experience",
          required: true,
          maxRating: 5,
          gridColumns: "full",
        },
        {
          id: "textarea_feedback",
          type: "textarea",
          label: "Additional Feedback",
          rows: 4,
          gridColumns: "full",
        },
        {
          id: "checkbox_contact",
          type: "checkbox",
          label: "Contact Permission",
          checkboxLabel: "You may contact me about my feedback",
          gridColumns: "full",
        },
        {
          id: "submit_survey",
          type: "submit",
          label: "Submit Survey",
          gridColumns: "full",
        },
      ],
    },
    {
      id: "eventRegistration",
      label: "Event Registration",
      icon: Ticket,
      components: [
        {
          id: "heading_event",
          type: "heading",
          label: "Event Registration",
          gridColumns: "full",
        },
        {
          id: "fullName_event",
          type: "fullName",
          label: "Attendee Name",
          required: true,
          gridColumns: "full",
        },
        {
          id: "email_event",
          type: "email",
          label: "Email Address",
          required: true,
          gridColumns: "2",
        },
        {
          id: "tel_event",
          type: "tel",
          label: "Phone Number",
          required: true,
          gridColumns: "2",
        },
        {
          id: "select_ticket",
          type: "select",
          label: "Ticket Type",
          options: ["General Admission", "VIP", "Early Bird", "Group (5+)"],
          required: true,
          gridColumns: "2",
        },
        {
          id: "number_quantity",
          type: "number",
          label: "Number of Tickets",
          min: 1,
          max: 10,
          required: true,
          gridColumns: "2",
        },
        {
          id: "checkbox_dietary",
          type: "checkbox",
          label: "Dietary Restrictions",
          checkboxLabel: "I have dietary restrictions",
          gridColumns: "full",
        },
        {
          id: "textarea_dietary",
          type: "textarea",
          label: "Please specify dietary restrictions",
          rows: 2,
          gridColumns: "full",
        },
        {
          id: "submit_event",
          type: "submit",
          label: "Register Now",
          gridColumns: "full",
        },
      ],
    },
    {
      id: "jobApplication",
      label: "Job Application",
      icon: Briefcase,
      components: [
        {
          id: "heading_job",
          type: "heading",
          label: "Job Application Form",
          gridColumns: "full",
        },
        {
          id: "fullName_job",
          type: "fullName",
          label: "Full Name",
          required: true,
          gridColumns: "full",
        },
        {
          id: "email_job",
          type: "email",
          label: "Email Address",
          required: true,
          gridColumns: "2",
        },
        {
          id: "tel_job",
          type: "tel",
          label: "Phone Number",
          required: true,
          gridColumns: "2",
        },
        {
          id: "select_position",
          type: "select",
          label: "Position Applied For",
          options: ["Software Developer", "UX Designer", "Product Manager", "Marketing Specialist", "Other"],
          required: true,
          gridColumns: "full",
        },
        {
          id: "file_resume",
          type: "file",
          label: "Resume/CV",
          accept: ".pdf,.doc,.docx",
          required: true,
          gridColumns: "full",
        },
        {
          id: "textarea_experience",
          type: "textarea",
          label: "Relevant Experience",
          rows: 4,
          required: true,
          gridColumns: "full",
        },
        {
          id: "date_available",
          type: "date",
          label: "Available Start Date",
          required: true,
          gridColumns: "full",
        },
        {
          id: "submit_job",
          type: "submit",
          label: "Submit Application",
          gridColumns: "full",
        },
      ],
    },
    {
      id: "feedbackForm",
      label: "Feedback Form",
      icon: MessageSquare,
      components: [
        {
          id: "heading_feedback",
          type: "heading",
          label: "Product Feedback",
          gridColumns: "full",
        },
        {
          id: "text_feedback_name",
          type: "text",
          label: "Your Name",
          gridColumns: "2",
        },
        {
          id: "email_feedback",
          type: "email",
          label: "Email Address",
          gridColumns: "2",
        },
        {
          id: "select_product",
          type: "select",
          label: "Product",
          options: ["Product A", "Product B", "Product C", "Service X", "Other"],
          required: true,
          gridColumns: "full",
        },
        {
          id: "starRating_feedback",
          type: "starRating",
          label: "Rate this product",
          required: true,
          maxRating: 5,
          gridColumns: "full",
        },
        {
          id: "feedbackTable_product",
          type: "feedbackTable",
          label: "Product Evaluation",
          feedbackFields: ["Ease of use", "Value for money", "Customer support", "Would recommend to others"],
          required: true,
          gridColumns: "full",
        },
        {
          id: "textarea_improvements",
          type: "textarea",
          label: "Suggested Improvements",
          rows: 4,
          gridColumns: "full",
        },
        {
          id: "image_screenshot",
          type: "image",
          label: "Upload Screenshot (Optional)",
          gridColumns: "full",
        },
        {
          id: "submit_feedback",
          type: "submit",
          label: "Submit Feedback",
          gridColumns: "full",
        },
      ],
    },
  ]

export default  FORM_TEMPLATES;